# Generated by Django 3.0.8 on 2020-08-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200807_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_product',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='API.customer'),
        ),
    ]
