# Generated by Django 3.0.8 on 2020-08-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200807_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csv_product',
            options={'get_latest_by': '-uploaded_date'},
        ),
    ]
