# Generated by Django 3.0.8 on 2020-08-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200807_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csv_product',
            options={'ordering': ('-uploaded_date',)},
        ),
    ]
